### ISSUE TITLE
Update sample code to use Appium 1.6.0

### ISSUE THREAD

**Issue by dpgraham** [appium/sample-code#101]
Sample code is currently incompatible with Appium 1.6.0, especially iOS 10 which uses XCUI testing.

**Comment by xwartz** [comment]
@imurchie @jlipps

**Comment by xwartz** [comment]
OK, i saw the [pr](https://github.com/appium/sample-code/pull/102)

**Comment by zmorris** [comment]
This worked for me with `git checkout dan-update-to-1_6_0` (specifically commit 006a072e7bdfed572fb2b108de5477a8c804984b) at least for `yarn run ios-simple` so far.

**Comment by jlipps** [comment]
The branch has been merged, thanks for your patience.
