### ISSUE TITLE
Add python examples using pytest fixtures

### ISSUE THREAD

**Issue by jamie-sherriff** [appium/sample-code#110]
Hello, would you guys accept a PR from me to show some examples that use a pytest fixture approach as i found it cleaner for doing my own tests?

If so how would you like this done, separate files or rewrite the existing ones?

**Comment by jlipps** [comment]
Hi @jamie-sherriff that would be amazing, please do. For now I would say separate files, or maybe the best idea is a separate dir like `pytest` inside the python section of the sample code? Then you can put whatever you want in that dir and it will be self-contained.

**Comment by jamie-sherriff** [comment]
Awesome will do, i like the idea of a separate directory as it then makes it easier to bundle a conftest without effecting the original tests.

**Comment by jamie-sherriff** [comment]
Closing as completed
