### ISSUE TITLE
Need help with ios safari redirection

### ISSUE THREAD

**Issue by akabirami** [appium/sample-code#117]
Hi,

My test case is to verify if the given link redirects to correct itunes link in ios safari. But the prb is safari is not able to open the link and the url changes to 0.0.0.0/welcome. Is there any way to check if the link in safari is redirecting to correct app store link? 

Using Appium 1.6.3 and wd.

**Comment by jlipps** [comment]
the sample code repo isn't a good place for help. please try https://discuss.appium.io.
