### ISSUE TITLE
Support append text for EditText in Android

### ISSUE THREAD

**Issue by ductrinhtien** [appium/sample-code#121]
Hi everyone,
Currently I use Appium by C# and I need to support a command that allow me append text after cursor.
For the current setImmediatValue. It also append text after cursor but if I append many time, it append at center of editText (not after curror).

Regards,
Duc Trinh

**Comment by jlipps** [comment]
This is not the right place for this discussion. Please visit the user forums or submit an issue to the main appium repo.
