### ISSUE TITLE
How to test that a button is `disabled`

### ISSUE THREAD

**Issue by stanislavkozlovski** [appium/sample-code#149]
On Android, I have disabled a button being able to get clicked until a certain condition is met within the input.
(Python client) 
The object currently has `clickable="false"` in the XML but the appium driver tells me different, because - `button.is_enabled()` returns `True`

**Comment by KazuCocoa** [comment]
In the case, you can get an arbitrary element with `el.get_attribute('clickable')`.
https://github.com/appium/python-client/blob/f37733dbd3dd79be97452a9ad98eb4a9325755ce/test/functional/ios/find_by_ios_class_chain_tests.py#L32
If your `xml` says the element is `disable`, you can see `false` by `el.get_attribute('clickable')`.


BTW, `enable` and `clickable` are https://stackoverflow.com/questions/15615823/setenabled-vs-setclickable-what-is-the-difference


If you have any issue, the page source and logs are helpful for us.
