### ISSUE TITLE
New to Appium, some general questions

### ISSUE THREAD

**Issue by lddd** [appium/sample-code#154]
Hey there,

i just recently heard about Appium and would like to know if its technically possible to automate a 3rd party App like WhatsApp with it to listen for incoming messages, sending messages, listing contacts and optional route such logic to a restful API to integrate with existing applications.

There are already some web automating approaches with Selenium here but i am not sure how fast/stable they are for such use case. 

I would appreciate any help and information on it.

**Comment by KazuCocoa** [comment]
sorry for the late reply...

> its technically possible to automate a 3rd party App like WhatsApp with it to listen for incoming messages, sending messages, listing contacts and optional route such logic to a restful API to integrate with existing applications.

Appium can. You can manage 3rd party apps installed on your devices. The stability depends on fundamentals framework provided by Google/Apple. Appium manages applications via UI level. So, it's slower than Espresso/EarlGrey if we compare UI level automation focused on functionality. But, maybe, the running speed handling 3rd party apps are similar.

http://appium.io/docs/en/about-appium/intro/
@lddd
