### ISSUE TITLE
The environment you requested was unavailable?

### ISSUE THREAD

**Issue by lddd** [appium/sample-code#155]
Hey there,

i am new to appium and would like to use node js / javascript as a client for a project i plan. Now running the demo

> npm run android-simple

throws the following error

>  Error: [init({"browserName":"","appium-version":"1.5","platformName":"Android","platformVersion":"4.4","deviceName":"AndroidTestDevice","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"})] The environment you requested was unavailable.

Appium server + Emulator is running, caps matching the device. 

What might be the problem here?

**Comment by saikrishna321** [comment]
Please refer https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio
