### ISSUE TITLE
Sample code for testing windows desktop app

### ISSUE THREAD

**Issue by ChillarAnand** [appium/sample-code#162]
How is the [app value for calculated here](https://github.com/appium/sample-code/blob/master/sample-code/examples/python/windows_calculatortest.py#L29)? How to get that value for 3rd party windows desktop apps?

I am trying to run a windows desktop app with appium, I tried giving it full path to exe file which also didn't work.

**Comment by KazuCocoa** [comment]
Did you see https://github.com/Microsoft/WinAppDriver ?
I have no experience for it, but the repository has some sample scripts. So, I think it will help you.
@ChillarAnand

**Comment by ChillarAnand** [comment]
@KazuCocoa Thanks.
