### ISSUE TITLE
Timing issue in Test code(simple_test.rb) for ruby

### ISSUE THREAD

**Issue by mrudulp** [appium/sample-code#53]
Hi,

Problem:
I noticed the sample code for ruby (simple_test.rb) fails.
I traced the reason down to line 90, `button('show alert').click`.

Probable Solution:
I believe probable solution would be to wait for element to appear.
`wait { button('show alert').click}`

Other Comments:
I have tried on my machine and suggested solution works.
I know previous line checks for dismissing of alert box, but I think code should wait for button to be visible again.

**Comment by Jonahss** [comment]
Oh great. Do you want to submit a Pull Request to change the test so it works?
