### ISSUE TITLE
arc complains "Don't know what to do with.." from desired capabilities 

### ISSUE THREAD

**Issue by jraczak** [appium/sample-code#60]
Followed the tutorials and looked directly and the `appium.txt` from the sample tests/apps. Running `arc` outputs the following.

justinr-mac:ApiDemos justinr$ arc
Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 3 char 1.
`- Don't know what to do with "deviceName" at line 3 char 1.
Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 3 char 1.
`- Don't know what to do with "deviceName" at line 3 char 1.
/Library/Ruby/Gems/2.0.0/gems/appium_lib-7.0.0/lib/appium_lib/driver.rb:324:in `initialize': platformName must be set. Not found in options: {:caps=>{:newCommandTimeout=>999999}} (RuntimeError)

I've tried several different formats of the appium.txt found around different tutorials and past issues. Current format is as follows.

[caps]
platformName = "android"
deviceName = “Android”
app = "/usr/local/lib/node_modules/appium/appium/samplecode/apps/ApiDemos/bin/ApiDemos-debug.apk’"
avd = “Google APIs”

**Comment by jlipps** [comment]
hi @jraczak! i had some similar problems when trying to use arc/appium.txt in the past. I'm not sure now how I resolved them. But @bootstraponline (creator of arc) can probably guide you in this.

**Comment by bootstraponline** [comment]
that error means your appium.txt file isn't valid [toml](https://github.com/toml-lang/toml). Start by copying a working [appium.txt](https://github.com/appium/ruby_lib/blob/master/android_tests/appium.txt) and go from there.

**Comment by bootstraponline** [comment]
`“` is not the same as `"`, where ever you copied the quotes from messed it up.

**Comment by jraczak** [comment]
@jlipps @bootstraponline Thanks for the super fast replies, gents! 

This was indeed the problem. Do you suppose there is an opportunity to call out somewhere that this file follows the TOML spec? It's easy to gloss over and therefor is an easy stumbling block, especially given OSX's 'smart quotes' replacement is on by default.

**Comment by bootstraponline** [comment]
I don't know of any programming language that works with smart quotes (this isn't a toml issue). I'd merge a PR if you'd like to update the readme.

**Comment by jraczak** [comment]
I'm not suggesting it work with pull quotes or that toml. I'm suggesting that it's quite probable for OSX users to encounter this issue without noticing it. 

I've not been working off the README but I'll take a look and see where it may make sense to contribute a change.
