### ISSUE TITLE
Sauce Labs connect Node example not working

### ISSUE THREAD

**Issue by tomtom87** [appium/sample-code#71]
I am trying to get the node js example working with Sauce Labs connect. I am running the

`SAUCE=1 mocha android-local-server.js`

As the documentation says, whilst running the Sauce labs connect tunnel. All I get is the following error and nothing on sauce labs:

```
  1) android local server "before all" hook:
     Error: [init({"browserName":"","appium-version":"1.3","platformName":"Android","platformVersion":"4.3","deviceName":"Android Emulator","name":"android - local server","tags":["sample"]})] The environment you requested was unavailable.
```

Help much appreciated

**Comment by Jonahss** [comment]
Appium-version is out of date. Try version 1.4.16

And try android version 4.4

**Comment by tomtom87** [comment]
Hi,

yeh I updated these with the generator on the documentation as it is 
back online now. The problem is the emulator doesn't have the apk loaded 
when the test starts and the saucelabs video only shows 50 seconds of 
the emulator loading up, with no apk. Then the test 'fails' but it did 
not even run.

I have tried contacting support but got no reply yet.

I have increased the timeout to 30,000 seconds. And retried. On a second 
test it just dies at 0 seconds, if I change a parameter it will run 
again, but for a maximum of 50 seconds. The video will show my app is 
not present on the sauce labs device.

I have tested this locally on a mac osx and a debian and a ubuntu 
machine it works flawlessly cannot get it to break here. Please let me 
know how to make this work, my boss is so stressed about it. I need to 
get iOS working next week and the board are going ape about saucelabs 
currently, i need a result.

Thanks

On 17/02/2559 BE 1:23 a.m., Jonah wrote:
>
> Appium-version is out of date. Try version 1.4.16
>
> And try android version 4.4
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/appium/sample-code/issues/71#issuecomment-184811300>.
>

-- 
--

Tom Whitbread
Gript.co.uk

**Comment by Jonahss** [comment]
Can you send me a link to your saucelabs job?

If the emulator does not have app, check your desired capabilities? What do you have in the "app" field? You can't have a local path to an app file, because the local path on your computer is not the local path on the Sauce VM. The "app" desired capability should either be a public url to download from, or you should be using [sauce storage](https://wiki.saucelabs.com/display/DOCS/Using+Sauce+Storage+for+Test+Assets)

**Comment by tomtom87** [comment]
Sure, please watch the video it's always just done this. U can check all 
of my users archive. It either runs for approx 50s or 0s.

URL: https://saucelabs.com/beta/tests/ec93e352feb04909910008d8470ba16d

The app field I have the sauce-storage: pressie-qa.apk which I verified 
and uploaded with the REST API as found in the documentation.

This all works fine locally. So I am going to AWS. Saucelabs just wasted 
over a whole week of my time messing about, I will be doing a charge 
back because I believe it is false advertising and I know i am not alone 
there are many many complaints all over the KB and forums.

On 19/02/2559 BE 3:07 a.m., Jonah wrote:
>
> Can you send me a link to your saucelabs job?
>
> If the emulator does not have app, check your desired capabilities? 
> What do you have in the "app" field? You can't have a local path to an 
> app file, because the local path on your computer is not the local 
> path on the Sauce VM. The "app" desired capability should either be a 
> public url to download from, or you should be using sauce storage 
> <https://wiki.saucelabs.com/display/DOCS/Using+Sauce+Storage+for+Test+Assets>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/appium/sample-code/issues/71#issuecomment-185894449>.
>

-- 
--

Tom Whitbread
Gript.co.uk

**Comment by upgundecha** [comment]
Hi,

I am getting similar `The environment you requested was unavailable.` error while trying to run tests with Sauce labs. Here're my desired caps:

```
 var desired = {
            deviceName: 'Samsung Galaxy S4 Emulator',
            platformVersion: '4.4',
            platformName: 'Android',
            name: 'Sample Test',
            app: 'sauce-storage:myapp.zip',
            "appPackage": "<package name>",
            "appActivity": "<activity name>"
         };
```
Really appreciate any help to get rid of this error.

Thanks,
Unmesh

**Comment by imurchie** [comment]
Try specifying `appiumVersion: '1.5.2'`.

**Comment by 7ynk3r** [comment]
Same problem here. The error messages are useless, impossible to know what is going on. Everything works locally but Sauce Labs doesn't.

**Comment by imurchie** [comment]
The sample code has been updated, in the main repository. For node, please see either
1. https://github.com/appium/appium/tree/master/sample-code/javascript-wd if you want to use [wd](https://www.npmjs.com/package/wd)
2. https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio if you want to use [webdriverio](https://www.npmjs.com/package/webdriverio)
