### ISSUE TITLE
Query: Why this repo has push permission to all users ?

### ISSUE THREAD

**Issue by vikramvi** [appium/sample-code#91]
I am doing some fixes in this repo as planned to submit PR.

After setting this as upstream repo , I observed below

upstream	git@github.com:appium/sample-code.git (fetch)
upstream	git@github.com:appium/sample-code.git (push)

Isn't upstream should have only fetch permission ?

**Comment by Jonahss** [comment]
HM.

I checked the github settings for the repo, looks like appium committers have admin access and java-client committers have write privileges.

Try pushing a minor change and let's see if it prevents you.

**Comment by vikramvi** [comment]
@Jonahss  got below error

ERROR: Permission to appium/sample-code.git denied to vikramvi.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Strangely why does upstream showing push tag as well ? Is this bug in GitHub ?

Regards,
Vikram

**Comment by Jonahss** [comment]
I think it just means that the upstream branch for pushing is github. If you wanted, you can set the push location to be different from the fetch location, but they're almost always the same.
